[workspace]
authors = ["igamenovoer <igamenovoer@gmail.com>"]
channels = ["conda-forge", "main"]
name = "gemini-robotics"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
